def role_map(role_num):
    if role_num==1:
        return 'province'
    elif role_num==2:
        return 'city'
    elif role_num==4:
        return 'agent1'
    elif role_num==5:
        return 'agent2'