# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('wx_nickname', models.CharField(max_length=255)),
                ('wx_name', models.CharField(max_length=255)),
            ],
        ),
    ]
