# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 08:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wx_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('wx_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wx_sex', models.IntegerField(blank=True, null=True)),
                ('wx_city', models.CharField(blank=True, max_length=255, null=True)),
                ('wx_province', models.CharField(blank=True, max_length=255, null=True)),
                ('wx_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('wx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=32)),
                ('id_card', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=30, null=True)),
                ('auth_key', models.CharField(blank=True, max_length=32, null=True)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('provcode', models.CharField(blank=True, max_length=10, null=True)),
                ('citycode', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.IntegerField(choices=[(0, '普通用户'), (1, '省'), (2, '市'), (3, '管理员'), (4, '一级代理'), (5, '二级代理')], default=0)),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '不正常')], default=0)),
                ('created', models.IntegerField(blank=True, null=True)),
                ('changed', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LottoOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('lotto_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('issue', models.CharField(blank=True, max_length=20, null=True)),
                ('multiple', models.IntegerField(blank=True, null=True)),
                ('follow', models.IntegerField(default=1)),
                ('payment', models.IntegerField(default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('status', models.IntegerField(default=-1)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.IntegerField(blank=True, null=True)),
                ('changed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('p3', models.IntegerField(blank=True, null=True)),
                ('p4', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
