# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0004_auto_20171114_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '省'), (2, '市'), (3, '管理员')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_sex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
