# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0005_auto_20171114_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LottoOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('lotto_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('issue', models.CharField(blank=True, max_length=20, null=True)),
                ('multiple', models.IntegerField(blank=True, null=True)),
                ('follow', models.IntegerField(default=1)),
                ('payment', models.IntegerField(default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('status', models.IntegerField(default=-1)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.IntegerField(blank=True, null=True)),
                ('changed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('p3', models.IntegerField(blank=True, null=True)),
                ('p4', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
