# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_model', '0006_agent_lottoorder_userrecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '省'), (2, '市'), (3, '管理员'), (1, '一级代理'), (2, '二级代理')], default=0),
        ),
    ]
