# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceSorted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('amount_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('add_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
